name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter_test_and_run:
    - name: Run flutter test and run app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v3
          with:
            java-version: '17'
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
        - run: flutter pub get
        - run: flutter --version
        - run: flutter analyze
        - run: flutter test
        - run: flutter build apk


